fmarket/urls.py
# from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from basis.views import create_order
from home.views import home
from account.views import SignUp, user_profile, account_menu, send_sms, registration_sms, login_view, submit_rating, update_username, update_avatar
from create_food.views import add_food, create_category, manage_category
from owner.views import get_orders
from oreders.views import orders_view, update_order_status, user_orders_json, orders_chart_view, update_order_courier_status
from edit_menu.views import edit_menu_view, edit_food_view, delete_food
from edit_profile.views import edit_profile_view
from profile_info.views import profile_view
from basis_admin.views import toggle_user_status
from courier.views import courier_page, register_or_login, get_courier_orders, pickup_order, get_orders_by_ids, courier_update_order_status
from shop_list.views import user_list
from dynamic_search.views import search_food_menu
from taxi_del.views import taxi
from taxi_driver.views import taxi_driver
from my_orders.views import my_orders, update_order_result_ajax, my_orders_ajax
from firebase_push.views import save_fcm_token


urlpatterns = [
    path('save-fcm-token/', save_fcm_token, name='save_fcm_token'),
    path('my-orders/', my_orders, name='my_orders'),
    path('my-orders-ajax/', my_orders_ajax, name='my_orders_ajax'),
    path('update-order-ajax/<int:order_id>/<str:result>/', update_order_result_ajax, name='update_order_result_ajax'),
    path("submit-rating/", submit_rating, name="submit_rating"),
    path('taxi_driver/', taxi_driver, name='taxi_driver'),
    path('taxi/', taxi, name='taxi'),
    path('update-username/', update_username, name='update_username'),
    path('update-avatar/', update_avatar, name='update_avatar'),
    path('sending/sms/', send_sms, name='send_sms'),
    path('registration/', registration_sms, name='registration_sms'),
    path('search/', search_food_menu, name='search_food_menu'),
    path('create-category/', create_category, name='create_category'),
    path('manage-category/', manage_category, name='manage_category'),
    path('category/<str:category>/', user_list, name='user_list'),
    path('pickup_order/<int:order_id>/', pickup_order, name='pickup_order'),
    path('courier_update_order_status/<int:order_id>/', courier_update_order_status, name='courier_update_order_status'),
    path('get_orders_by_ids/', get_orders_by_ids, name='get_orders_by_ids'),
    path('get_courier_orders/', get_courier_orders, name='get_courier_orders'),
    path('update_order_courier_status/<int:order_id>/', update_order_courier_status, name='update_order_courier_status'),
    path('courier/orders/', courier_page, name='courier_page'),
    path('register_or_login/', register_or_login, name='register_or_login'),
    path('toggle-status/', toggle_user_status, name='toggle_user_status'),
    path('profile/', profile_view, name='profile'),
    path('edit-profile/', edit_profile_view, name='edit_profile'),
    path('edit-menu/', edit_menu_view, name='edit_menu'),
    path('delete_food/<int:id>/', delete_food, name='delete_food'),
    path('edit-food/<int:food_id>/', edit_food_view, name='edit_food'),
    path('orders-chart/', orders_chart_view, name='orders_chart'),  # показать на странице график json статистика
    path('user-orders-json/', user_orders_json, name='user_orders_json'),  # запрос на создание json статистика
    path('user/<int:user_id>/', user_profile, name='user_profile'),
    path('account/<int:user_id>/', account_menu, name='account_menu'),
    path('orders/', orders_view, name='orders'),
    path('get-orders/', get_orders, name='get_orders'),
    path('update-order-status/', update_order_status, name='update_order_status'),
    path('', home, name='home'),
    path('account/', include('django.contrib.auth.urls')),
    path("signup/", SignUp, name="signup"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('add/', add_food, name='add_food'),
    path('create-order/', create_order, name='create_order'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basis/models.py
from account.models import CustomUser
from django.db import models
from django.utils import timezone
from django.conf import settings
from decimal import Decimal, ROUND_HALF_UP
import os


class UserFCMToken(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)






class FoodCategory(models.Model):
    name = models.CharField(max_length=50, unique=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='categories'
    )

    def __str__(self):
        return self.name


def ad_screen_img_path(instance, filename):
    return os.path.join('static', 'media', 'foodimages', 'foodimg', filename)


def food_image_one_path(instance, filename):
    return os.path.join('static', 'media', 'foodimages', filename)


def order_bank_check_path(instance, filename):
    return os.path.join('static', 'media', 'orders_bank_check', filename)



class Food_menu(models.Model):
    STATUS_FOOD = [
        ('True', 'В наличии'),
        ('False', 'Отсутствует'),
    ]

    name = models.TextField(max_length=50)
    description = models.TextField(max_length=800)
    price = models.DecimalField(max_digits=10, decimal_places=0, default='10')
    discount_percent = models.PositiveIntegerField(default=0)  # 0–100
    discount_active = models.BooleanField(default=False)
    category = models.ForeignKey(
        FoodCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='foods'
    )
    food_status = models.CharField(max_length=20, choices=STATUS_FOOD, default='True')
    adscreenimg = models.ImageField(upload_to=ad_screen_img_path)
    imageOne = models.ImageField(upload_to=food_image_one_path)
    date_add = models.DateField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    click_order = models.PositiveIntegerField(default=0)

    @property
    def final_price(self):
        if self.discount_active and self.discount_percent > 0:
            discount = (self.price * Decimal(self.discount_percent)) / Decimal(100)
            final = self.price - discount
            return final.quantize(Decimal('1'), rounding=ROUND_HALF_UP)
        return self.price

    def delete(self, *args, **kwargs):
        self.delete_images()
        super(Food_menu, self).delete(*args, **kwargs)

    def delete_images(self):
        images = [self.adscreenimg, self.imageOne]
        for image_field in images:
            if image_field:
                if os.path.exists(image_field.path):
                    os.remove(image_field.path)

    def save(self, *args, **kwargs):
        # 🔥 Удаление старых файлов при обновлении изображения
        if self.pk:
            old = Food_menu.objects.get(pk=self.pk)

            for field in ['adscreenimg', 'imageOne']:
                old_file = getattr(old, field)
                new_file = getattr(self, field)

                if old_file and old_file != new_file:
                    if os.path.exists(old_file.path):
                        os.remove(old_file.path)

        if not self.date_add:
            self.date_add = timezone.now()

        # Авто статус по количеству — только если auto_status=True
        auto_status = kwargs.pop('auto_status', True)
        if auto_status:
            if self.quantity <= 0:
                self.food_status = 'False'
            elif self.food_status not in ['True', 'False']:
                self.food_status = 'True'

        super().save(*args, **kwargs)


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('in_progress', 'В процессе'),
        ('completed', 'Успешно'),
        ('cancelled', 'Отменен'),
    ]
    ORDER_PAYMENT_STATUS = [
        ('Online', 'Онлайн'),
        ('Offline', 'Наличными'),
    ]
    ORDER_DELIVERY_STATUS = [
        ('Delivery', 'Доставка курьером'),
        ('Pickup', 'Самовывоз'),
    ]

    COURIER_STATUS = [
        ('expectation', 'Ожидание'),
        ('called', 'Вызываем курьера'),
        ('pick_up', 'Забирает заказ'),
        ('on_the_way', 'В пути'),
        ('delivered', 'Доставлено'),
        ('canceled', 'Отменено'),
    ]

    DELIVERY_RESULT_CHOICES = [
        ('none', 'Не выбран'),
        ('success', 'Завершен успешно'),
        ('failed', 'Заказ не приехал'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    delivery_result = models.CharField(max_length=20, choices=DELIVERY_RESULT_CHOICES, default='none')
    courier_first_name = models.CharField(max_length=15, blank=True)
    courier_last_name = models.CharField(max_length=15, blank=True)
    courier_tel_number = models.CharField(max_length=15, blank=True)
    courier_car = models.CharField(max_length=40, blank=True)
    courier_car_number = models.CharField(max_length=15, blank=True)
    courier_status = models.CharField(max_length=30, choices=COURIER_STATUS, default='expectation')

    order_number = models.CharField(max_length=255, unique=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_user_name = models.CharField(max_length=100)
    user_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    order_details = models.TextField()
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='in_progress')
    order_tel_number = models.CharField(max_length=14)
    order_adsress = models.CharField(max_length=100)
    order_bank_check = models.ImageField(upload_to=order_bank_check_path, blank=True, null=True)
    order_payment_status = models.CharField(max_length=100)
    order_delivery_status = models.CharField(max_length=100)
    order_city = models.CharField(max_length=14, blank=True)



    def __str__(self):
        return self.order_number



# from fcm_django.models import FCMDevice
# FCMDevice.objects.all()

# python manage.py shell
# Create your models here.
# python manage.py makemigrations basis
# python manage.py migrate
# python manage.py runserver
# python manage.py runsslserver --certificate cert.pem --key key.pem
# python manage.py runsslserver 192.168.0.101:8000 --certificate cert.pem --key key.pem
# citizenfour0
# underground023
# & "C:/Users/Admin/PycharmProjects/Findy_store/venv/Scripts/activate.ps1"
# cd fmarket
# python manage.py runserver
# python manage.py runserver 192.168.0.103:8000
# python manage.py createsuperuser source venv/bin/activate pip install -r req.txt
# amandows@mail.ru citizenfour0
# pip install
#         android:networkSecurityConfig="@xml/network_security_config"

create_food/models.py
from django.db import models

# Create your models here.

create_food/forms.py
from django import forms
from basis.models import Food_menu, FoodCategory

class FoodMenuForm(forms.ModelForm):
    class Meta:
        model = Food_menu
        fields = ['name', 'description', 'price', 'category', 'imageOne', 'food_status']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получаем пользователя из kwargs
        super().__init__(*args, **kwargs)
        if user:
            self.fields['category'].queryset = FoodCategory.objects.filter(user=user)

create_food/views.py
import json
from django.shortcuts import render, redirect
from .forms import FoodMenuForm
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO
from basis.models import FoodCategory, Food_menu
from django.http import JsonResponse
from django.core.cache import cache
import datetime


def create_category(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            name = data.get('name')

            if not name:
                return JsonResponse({'success': False, 'error': 'Name is required'}, status=400)

            category = FoodCategory(name=name, user=request.user)
            category.save()
            return JsonResponse({'success': True})

        except json.JSONDecodeError:
            return JsonResponse({'success': False, 'error': 'Invalid JSON'}, status=400)

        except Exception as e:
            print(f"Error: {e}")  # Логирование ошибки
            return JsonResponse({'success': False, 'error': str(e)}, status=500)

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=400)



def add_food(request):
    if request.method == 'POST':
        form = FoodMenuForm(request.POST, request.FILES)
        if form.is_valid():
            food = form.save(commit=False)
            food.user = request.user

            # Обработка изображений перед сохранением
            for field_name in ['imageOne']:
                image_field = getattr(food, field_name)
                if image_field:
                    image = Image.open(image_field)
                    output = BytesIO()
                    image.save(output, format='JPEG', quality=40)
                    output.seek(0)
                    image_field.file = output

            if food.imageOne:
                img_one = Image.open(food.imageOne)
                width, height = img_one.size
                target_width = 500
                target_height = 500
                if width > height:
                    new_width = target_width
                    new_height = int(target_width * (height / width))
                else:
                    new_height = target_height
                    new_width = int(target_height * (width / height))
                resized_image = img_one.resize((new_width, new_height))
                output = BytesIO()
                resized_image.save(output, format='JPEG', quality=60)
                output.seek(0)
                food.adscreenimg.save('filename.jpg', ContentFile(output.read()))

            food.save()
            # Удаляем кэш для этого пользователя
            cache_key = f"foods_shuffle_{food.user.id}_{datetime.date.today()}"
            cache.delete(cache_key)
            return redirect('add_food')  # Измените на URL, куда вы хотите перенаправлять после сохранения
    else:
        form = FoodMenuForm(user=request.user)  # **Передаем user в форму**
    return render(request, 'create_food/create_food.html', {'form': form})


def manage_category(request):
    if request.method == "POST":
        data = json.loads(request.body)
        category_id = data.get("id")
        action = data.get("action")
        new_name = data.get("name")

        try:
            category = FoodCategory.objects.get(id=category_id, user=request.user)

            # ✏️ Переименование
            if action == "edit":
                if not new_name:
                    return JsonResponse({'success': False, 'error': 'Введите имя'})

                category.name = new_name
                category.save()

                return JsonResponse({'success': True, 'message': 'Категория обновлена'})

            # 🗑️ Удаление
            if action == "delete":
                # Находим ВСЕ товары этого пользователя с этой категорией
                foods = Food_menu.objects.filter(
                    user=request.user,
                    category=category
                )

                for food in foods:
                    food.delete()  # <-- тут вызовется delete_images()

                category.delete()

                return JsonResponse({'success': True, 'message': 'Категория и все товары удалены'})


        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})

    return JsonResponse({'success': False})

templates/create_food/create_food.html
{% extends 'basis/basis_admin.html' %}


{% block link %}
<link rel="stylesheet" href="/static/css/create_food.css">
{% endblock %}

{% block main %}

<div class="main">
    <h1 class="title">Добавить новый товар или создать категорию</h1>
    <div class="add_view_bts">
        <button class="add_menu">Добавить товар</button>
        <button class="add_category">Добавить категорию</button>
    </div>
    <form method="post" enctype="multipart/form-data" class="add_menu_form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            <label for="id_name">Название (Лагман, Манты):</label>
            {{ form.name }}
        </div>
        <div>
            <label for="id_description">Информация (состав и т.д):</label>
            {{ form.description }}
        </div>
        <div>
            <label for="id_price">Цена:</label>
            {{ form.price }}
        </div>
        <div>
            <label for="id_category">Категория:</label>
            {{ form.category }}
        </div>
        <div>
            <label for="id_imageOne">Изображение:</label>
            {{ form.imageOne }}
        </div>
        <div>
            <label for="id_food_status">Статус продукта:</label>
            {{ form.food_status }}
        </div>
        <button type="submit">Добавить товар</button>
    </form>
    <form id="category-form" class="add_category_form">
        {% csrf_token %}
        <label for="category-name">Имя новой категории:</label>
        <div class="input_container">
            <input type="text" name="name" id="category-name" required class="category-name"
                placeholder="Введите название категории">
            <button type="submit" class="submit">Создать категорию</button>
        </div>
    </form>
    <div class="my-categories">
        <h3>Мои категории товаров:</h3>
        {% for cat in request.user.categories.all %}
        <div class="cat-row" data-id="{{cat.id}}">
            <input type="text" value="{{cat.name}}" class="cat-input">
            <button class="save-cat">Сохранить</button>
            <button class="delete-cat">Удалить</button>
        </div>
        {% endfor %}
    </div>

</div>


<script>
    document.getElementById('category-form').addEventListener('submit', function (e) {
        e.preventDefault();  // Предотвращает стандартную отправку формы

        createCategory();  // Вызывает функцию для отправки данных через fetch
    });

    const createCategory = async () => {
        const name = document.getElementById('category-name').value;
        const response = await fetch('/create-category/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken') // Убедитесь, что CSRF токен добавлен
            },
            body: JSON.stringify({ name: name })
        });

        const data = await response.json();

        if (data.success) {
            alert('Категория создана');
            location.reload();
        } else {
            console.error('Ошибка:', data.error);
            alert('Произошла ошибка: ' + data.error);
        }
    };


</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const btnMenu = document.querySelector('.add_menu');
        const btnCategory = document.querySelector('.add_category');

        const formMenu = document.querySelector('.add_menu_form');
        const formCategory = document.querySelector('.add_category_form');
        const myCategories = document.querySelector('.my-categories')

        // по умолчанию
        formMenu.style.display = 'flex';
        formCategory.style.display = 'none';

        btnMenu.addEventListener('click', function () {
            formMenu.style.display = 'flex';
            formCategory.style.display = 'none';
            myCategories.style.display = 'none'
            btnMenu.style.cssText = 'background-color: #131313; color: #ffffff;'
            btnCategory.style.cssText = 'background-color: #ffffff; color: #131313;'
        });

        btnCategory.addEventListener('click', function () {
            formMenu.style.display = 'none';
            formCategory.style.display = 'flex';
            myCategories.style.display = 'flex'
            btnCategory.style.cssText = 'background-color: #131313; color: #ffffff;'
            btnMenu.style.cssText = 'background-color: #ffffff; color: #131313;'
        });
    });
</script>
<script>
    document.querySelectorAll('.cat-row').forEach(row => {
        const id = row.dataset.id;
        const input = row.querySelector('.cat-input');

        row.querySelector('.save-cat').onclick = async () => {
            const res = await fetch('/manage-category/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                body: JSON.stringify({
                    id: id,
                    action: 'edit',
                    name: input.value
                })
            });

            const data = await res.json();
            alert(data.message);
            location.reload();
        };

        row.querySelector('.delete-cat').onclick = async () => {
            if (!confirm('Удалить категорию?')) return;

            const res = await fetch('/manage-category/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                body: JSON.stringify({
                    id: id,
                    action: 'delete'
                })
            });

            const data = await res.json();
            alert(data.message);
            location.reload();
        };
    });
</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {

        document.querySelectorAll('.cat-row').forEach(row => {
            const input = row.querySelector('.cat-input');
            const btnSave = row.querySelector('.save-cat');
            const btnDelete = row.querySelector('.delete-cat');

            const originalValue = input.value;

            // дефолт
            btnSave.style.display = 'none';
            btnDelete.style.display = 'inline-block';

            input.addEventListener('input', function () {
                if (input.value.trim() !== originalValue.trim()) {
                    btnSave.style.display = 'inline-block';
                    btnDelete.style.display = 'none';
                } else {
                    btnSave.style.display = 'none';
                    btnDelete.style.display = 'inline-block';
                }
            });
        });

    });
</script>







{% endblock %}