fmarket/urls.py
# from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from basis.views import create_order
from home.views import home
from account.views import SignUp, user_profile, account_menu, send_sms, registration_sms, login_view, submit_rating, update_username, update_avatar
from create_food.views import add_food, create_category, manage_category
from owner.views import get_orders
from oreders.views import orders_view, update_order_status, user_orders_json, orders_chart_view, update_order_courier_status
from edit_menu.views import edit_menu_view, edit_food_view, delete_food
from edit_profile.views import edit_profile_view
from profile_info.views import profile_view
from basis_admin.views import toggle_user_status
from courier.views import courier_page, register_or_login, get_courier_orders, pickup_order, get_orders_by_ids, courier_update_order_status
from shop_list.views import user_list
from dynamic_search.views import search_food_menu
from taxi_del.views import taxi
from taxi_driver.views import taxi_driver
from my_orders.views import my_orders, update_order_result_ajax, my_orders_ajax
from firebase_push.views import save_fcm_token


urlpatterns = [
    path('save-fcm-token/', save_fcm_token, name='save_fcm_token'),
    path('my-orders/', my_orders, name='my_orders'),
    path('my-orders-ajax/', my_orders_ajax, name='my_orders_ajax'),
    path('update-order-ajax/<int:order_id>/<str:result>/', update_order_result_ajax, name='update_order_result_ajax'),
    path("submit-rating/", submit_rating, name="submit_rating"),
    path('taxi_driver/', taxi_driver, name='taxi_driver'),
    path('taxi/', taxi, name='taxi'),
    path('update-username/', update_username, name='update_username'),
    path('update-avatar/', update_avatar, name='update_avatar'),
    path('sending/sms/', send_sms, name='send_sms'),
    path('registration/', registration_sms, name='registration_sms'),
    path('search/', search_food_menu, name='search_food_menu'),
    path('create-category/', create_category, name='create_category'),
    path('manage-category/', manage_category, name='manage_category'),
    path('category/<str:category>/', user_list, name='user_list'),
    path('pickup_order/<int:order_id>/', pickup_order, name='pickup_order'),
    path('courier_update_order_status/<int:order_id>/', courier_update_order_status, name='courier_update_order_status'),
    path('get_orders_by_ids/', get_orders_by_ids, name='get_orders_by_ids'),
    path('get_courier_orders/', get_courier_orders, name='get_courier_orders'),
    path('update_order_courier_status/<int:order_id>/', update_order_courier_status, name='update_order_courier_status'),
    path('courier/orders/', courier_page, name='courier_page'),
    path('register_or_login/', register_or_login, name='register_or_login'),
    path('toggle-status/', toggle_user_status, name='toggle_user_status'),
    path('profile/', profile_view, name='profile'),
    path('edit-profile/', edit_profile_view, name='edit_profile'),
    path('edit-menu/', edit_menu_view, name='edit_menu'),
    path('delete_food/<int:id>/', delete_food, name='delete_food'),
    path('edit-food/<int:food_id>/', edit_food_view, name='edit_food'),
    path('orders-chart/', orders_chart_view, name='orders_chart'),  # показать на странице график json статистика
    path('user-orders-json/', user_orders_json, name='user_orders_json'),  # запрос на создание json статистика
    path('user/<int:user_id>/', user_profile, name='user_profile'),
    path('account/<int:user_id>/', account_menu, name='account_menu'),
    path('orders/', orders_view, name='orders'),
    path('get-orders/', get_orders, name='get_orders'),
    path('update-order-status/', update_order_status, name='update_order_status'),
    path('', home, name='home'),
    path('account/', include('django.contrib.auth.urls')),
    path("signup/", SignUp, name="signup"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('add/', add_food, name='add_food'),
    path('create-order/', create_order, name='create_order'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from basis.city_of_kg import CITY
import os
description_txt = ' Рабочий день: ПН-ВС \n Время работы: 08:00-23:00 \n Адресс: ул. Ленина 55 '

def user_logo_path(instance, filename):
    return os.path.join('static', 'media', 'user', 'logo', filename)


def user_logo_mini_path(instance, filename):
    return os.path.join('static', 'media', 'user', 'logo', filename)


def user_mbank_qr_path(instance, filename):
    return os.path.join('static', 'media', 'user', 'qr', filename)


def user_rsk_qr_path(instance, filename):
    return os.path.join('static', 'media', 'user', 'qr', filename)


class UserInfo(models.Model):
    user_phone_number = models.DecimalField(max_digits=9, decimal_places=0, blank=True, null=True)
    sms_code = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return self.user_phone_number


class UserRating(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ratings"   # оценки, полученные пользователем
    )
    rated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="given_ratings"  # оценки, которые поставил пользователь
    )
    score = models.PositiveSmallIntegerField()  # 1..5
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "rated_by")  # один пользователь — одна оценка для target
        indexes = [
            models.Index(fields=["user"]),
        ]

    def __str__(self):
        return f"{self.rated_by} -> {self.user}: {self.score}"


class CustomUser(AbstractUser):
    city = models.CharField(
        max_length=50,
        choices=CITY,
        default="Неизвестно"
    )
    USER_TYPES = [
        ('ordinary_user', 'Обычный пользователь'),
        ('food_user', 'Пользователь еда'),
        ('shop_user', 'Пользователь магазин'),
        ('taxi_user', 'Водитель такси'),
        ('courier_user', 'Водитель курьер'),
        ('taxi_company_user', 'Владелец таксопарк'),
    ]
    user_type = models.CharField(max_length=20, choices=USER_TYPES, default='ordinary_user')
    user_name = models.CharField(max_length=25, blank=True, null=True)
    user_description = models.CharField(max_length=500, default=description_txt, blank=True, null=True)
    user_phone_number = models.DecimalField(max_digits=9, decimal_places=0, blank=True, null=True)
    user_phone_number2 = models.DecimalField(max_digits=9, decimal_places=0, blank=True, null=True)
    user_mbank_qr = models.ImageField(upload_to=user_mbank_qr_path, blank=True, null=True)
    user_rsk_qr = models.ImageField(upload_to=user_rsk_qr_path, blank=True, null=True)
    user_mbank_link = models.CharField(max_length=500, blank=True, null=True)
    user_obank_link = models.CharField(max_length=500, blank=True, null=True)
    user_rsk_link = models.CharField(max_length=500, blank=True, null=True)
    user_abank_link = models.CharField(max_length=500, blank=True, null=True)

    user_raiting = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
    balance = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)

    CATEGORY_OF_EDUCATION = [
        ('', ''),
        ('Food', 'Еда'),
        ('Vegetables', 'Овощи'),
        ('Shop', 'Магазин'),
    ]
    category_of_education = models.CharField(max_length=20, choices=CATEGORY_OF_EDUCATION, default='', blank=True, null=True)

    SUB_CATEGORY_OF_EDUCATION = [
        ('', ''),
        ('Grocery', 'Продуктовый'),
        ('Vegetables', 'Электроника'),
        ('Clothes', 'Одежды'),
        ('Office', 'Канцелярия'),
    ]

    sub_category_of_education = models.CharField(max_length=20, choices=SUB_CATEGORY_OF_EDUCATION, blank=True, null=True, default='')

    USER_STATUS = [
        ('', ''),
        ('Online', 'Онлайн'),
        ('Offline', 'Оффлайн'),
    ]
    user_status = models.CharField(max_length=20, choices=USER_STATUS, default='', blank=True, null=True)
    user_logo = models.ImageField(upload_to=user_logo_path, blank=True, null=True)
    user_logo_mini = models.ImageField(upload_to=user_logo_mini_path, blank=True, null=True)

    USER_BLOCKED = [
        ('', ''),
        ('Yes', 'Да'),
        ('No', 'Нет'),
    ]
    user_blocked = models.CharField(max_length=20, choices=USER_BLOCKED, default='No')

    # Добавляем related_name для полей groups и user_permissions
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        related_name='custom_user_set',  # Пример названия, которое можно выбрать
        related_query_name='user',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_set',  # Пример названия, которое можно выбрать
        related_query_name='user',
    )

    def save(self, *args, **kwargs):
        try:
            old = CustomUser.objects.get(pk=self.pk)
        except CustomUser.DoesNotExist:
            old = None

        super().save(*args, **kwargs)  # сначала сохранить НОВЫЙ файл

        # ---------- Удаление старых файлов ----------
        if old:
            for field in ['user_logo', 'user_logo_mini']:
                old_file = getattr(old, field)
                new_file = getattr(self, field)

                if old_file and old_file != new_file:
                    if os.path.isfile(old_file.path):
                        os.remove(old_file.path)


    def __str__(self):
        return self.username if self.username else "Unnamed User"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        pass
        # CustomUser.objects.create(email=instance.email)




class Courier(models.Model):
    login = models.CharField(max_length=20)
    password = models.CharField(max_length=20, unique=True)
    first_name = models.CharField(max_length=15, unique=True)
    last_name = models.CharField(max_length=15, unique=True)
    tel_number = models.CharField(max_length=15, unique=True)
    car = models.CharField(max_length=30, unique=True)
    car_number = models.CharField(max_length=15, unique=True)
    city = models.CharField(max_length=50, default="Неизвестно")

    def __str__(self):
        return self.car_number

taxi_driver/models.py
from django.db import models

# Create your models here.

taxi_driver/views.py
from django.shortcuts import render

def taxi_driver(request):
    return render(request, 'taxi_driver/taxi_driver.html')

templates/taxi_driver/taxi_driver.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Водитель</title>
    <link rel="stylesheet" href="/static/css/taxi_driver.css">
</head>

<body>
    {% csrf_token %}
    <header>
        <div class="header-top">
            <div class="menu-btn">
                <button class="aside-btn"></button>
            </div>
            <a href="{% url 'taxi_driver' %}" class="logo">
                <p>FindyTaxi</p>
            </a>
            {% if request.user.is_authenticated %}
            <p class="user_name">{{ request.user.username }}</p>
            {% else %}
            <!-- <a href="{% url 'registration_sms' %}" class="login">
                    <p>Гость</p>
                </a> -->
            <a href="https://2gis.ru/routeSearch/rsType/car/from/-/to/72.73369215,41.64324689" class="login">
                <p>Гость</p>
            </a>
            {% endif %}
            <div class="aside-menu">
                <div class="administrator">
                    <div class="text-content">
                        <h2 class="name">{{ request.user.user_name }}</h2>
                        <p class="info">{{ request.user.get_user_type_display }}</p>
                    </div>
                    <div class="image-contaiener">
                        <img src="{{ request.user.user_logo.url }}" alt="">
                    </div>
                </div>

                <div class="aside-content">
                </div>
                <div class="footer">
                    <div class="soccial">
                        <a href="" class="facebook"></a>
                        <a href="" class="instagram"></a>
                        <a href="" class="twitter"></a>
                        <a href="" class="youtube"></a>
                    </div>
                    <div class="footer-text">
                        <p>ⓒ 2026 FindyMarket</p>
                        <p>Все права защищены</p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="maps" id="map_container"></div>
        <div class="step_one">
            <div class="findy_title">
                <p>Я Водитель</p>
                <img src="/static/icons/taxi-svgrepo-com.svg" alt="" class="title_logo">
            </div>
            <button class="radar-btn" id="goBtn">
                <span class="label">На линию</span>
                <div class="rings"></div>
                <div class="sweep"></div>
            </button>
            <button class="my_statistic">
                <p>Инфо</p>
            </button>
            <button class="options">
                <p>Опции</p>
            </button>
            <button class="my_location">
                <p>Обновить мое местоположение</p>
            </button>
        </div>
    </main>
    <script src="https://mapgl.2gis.com/api/js/v1"></script>
    <script src="/static/script/taxi_driver.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const userNameElement = document.querySelector(".user_name");

            if (userNameElement) {
                const fullNumber = userNameElement.textContent.trim(); // Получаем полный номер
                const lastFourDigits = fullNumber.slice(-4); // Извлекаем последние 4 цифры
                userNameElement.textContent = lastFourDigits; // Заменяем текст в элементе
            }
        });
    </script>
</body>

</html>